config/routes.rb
  
Rails.application.routes.draw do
  resources :subscriptions
  resources :users
  resources :comments, except: [:show, :index]
  resources :replies, except: [:show, :index]
  
  resources :articles, only: [:index] do
    resources :comments, only: [:index]
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  post 'logout' => 'sessions#destroy'

  get '/top' => 'articles#show' 
  #code challenge

  get 'articles/:id/comments/:id/replies/new' => 'replies#new'
  post 'articles/:id/comments/:id/replies/new' => 'replies#create'

  root to: 'articles#index'

  match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get, :post]
  # match '*path' => 'application#fallback', via: :all, constraints: lambda { |req| req.path.exclude? 'rails/active_storage'}


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    has_many :users, through: :comments
    has_many :replies, through: :comments
    validates :title, uniqueness: true
    accepts_nested_attributes_for :comments
    paginates_per 20

    def self.by_source(source)
        where(source: source)
    end 

    def self.all_sources
        Article.pluck(:source).uniq.sort
    end

    def self.search_bar(title)
        where('LOWER (title) LIKE ?', "%#{title.downcase}%")
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :require_login
    before_action :redirect_if_article_not_found, only: [:create, :update]
    
    def index
        # Api.load_data     #<----Uncomment to explicitly seed articles
        @users = User.all
        @comment = Comment.new
        filter_and_paginate_articles
    end

    def create
        redirect_to articles_path
    end

    def update
        find_article
        if @article.update(article_params)
            redirect_to articles_path
        else
            render :show
        end

    end

    def show
        @article = Article.all.max_by{|a| (a.comments.length + a.replies.length)}
    
    end

    private
    def find_article
        @article = Article.find_by_id(params[:id])
    end

    def article_params
        params.require(:article).permit(comment_attributes: [:content])
    end

    def redirect_if_article_not_found
        redirect_to articles_path unless @article
    end

    def filter_and_paginate_articles
        if !params[:source].blank?
            articles = Article.by_source(params[:source])
            @articles = Kaminari.paginate_array(articles).page(params[:page]).per(10)
        elsif !params[:title].blank?
            articles = Article.search_bar(params[:title])
            @articles = Kaminari.paginate_array(articles).page(params[:page]).per(10)
            
        else
            articles = Article.all.sort_by(&:published_at).reverse
            @articles = Kaminari.paginate_array(articles).page(params[:page]).per(10)
        end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3"><strong>Welcome to <*DivisioN*> News!</strong></h1>
          <p>DivisioN News is your go-to source for the most recent and controversial news stories from around the globe. Here at DivisioN, you can unnecessarily post your unwanted opinions on subjects no one in real life actually cares about, and argue with others about their own personal opinions and beliefs! Because thats what the world needs more of. MORE DIVISION!</p>
          <p>Click below to start Arguing!</p>
          <p><a class="btn btn-primary btn-lg" href="/users/<%=current_user.id%>" role="button">Argue with others &raquo;</a></p>
        </div>
      </div>

      <div class="container">
            <div class="text-center">
              <h3>Filter Source:</h3>
              <%= form_tag("/articles", method: "get") do %>
              <%= label_tag("Source")%>

              <%= select_tag "source", options_for_select(Article.all_sources), include_blank: true %>
              <%= submit_tag "Filter" %>
              <% end %>
            </div>

            <div class="row">
                <div class="col-md-9">

                  
                    <%@articles.each do |article|%>
                    <% article.comments.each do |r| r.replies%>
                    <% end %>

                    <ul class="card text-center border-dark mb-3 shadow-sm p-3 bg-white rounded">
                        <h2><strong><%= article.title %></h2></strong><br>
                        <h4 class="text-center card border-secondary p-2">Source: <%=article.source%></h4>
                        <p><em><%= article.description.first(250)%></em></p>
                        <p> <%=link_to "View Details:", article.url, class: "btn btn-secondary",    role: "button"%>&nbsp <%=link_to "Comments: (#{article.comments.length + article.replies.length})   ", article_comments_path(article), class: "btn btn-secondary" %></p>
                    </ul>

                    <% end %>
                </div>

                <div class="col-md-3">
                    <div class="list-group">    
                        
                        <%@users.each do |u| %>
                        <% if u.avatar.attached? %>
                        <li class="list-group-item list-group-item-action list-group-item-dark bg-secondary" ><img src="<%=(url_for(u.avatar)) %>" style="width: 50px; height: 50px; border-radius: 50px"> &nbsp&nbsp <%=link_to "#{u.username}", user_path(u), class: "text-light" %></li>
                        <% end %>
                    
      
                        <% end %>  
                    </div>
                </div>

            </div>
        </div> <!-- /container -->

        <div class="container-fluid col-4">
            <%= paginate @articles %>
        </div>  
  

        




    </main>

    <footer class="container-fluid col-3">
      <p>&copy; 2021 2-Slice-Gaming</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/articles/show.html.erb
<p><%= @article.title %></p>
<p><%= @article.author %></p>
<p><%= @article.description %></p>
<p><%= @article.comments.count %></p>