config/routes.rb
  
Rails.application.routes.draw do
  resources :subscriptions
  resources :users
  resources :comments, except: [:show, :index]
  resources :replies, except: [:show, :index]
  
  resources :articles, only: [:index] do
    resources :comments, only: [:index]
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  post 'logout' => 'sessions#destroy'

  get '/top' => 'articles#show' 
  #code challenge

  get 'articles/:id/comments/:id/replies/new' => 'replies#new'
  post 'articles/:id/comments/:id/replies/new' => 'replies#create'

  root to: 'articles#index'

  match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get, :post]
  # match '*path' => 'application#fallback', via: :all, constraints: lambda { |req| req.path.exclude? 'rails/active_storage'}


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/partials/_comments.html.erb
<div class="container mb-5 mt-5">
    <div class="card">
        <div class="row">
            <div class="col-md-12">
            
                <h3 class="text-center mb-5"> Ready: FIGHT! </h3>
                <%= render partial: 'partials/errors', locals: {instance: @comment} %>
                <%=form_for @comment do |f|%>
                <%=f.hidden_field :article_id, :value=> @article.id%>
                <%=f.label :content, 'Comment:' %><br>
                <%=f.text_area :content %><br>
                <%=f.submit %>
                <%end%>
                <br>
             
                
                <% @article.comments.each do |c| %>

                    <div class="row pb-4">
                        <div class="col-md-12">
                            <div class="media">    
                                <% if c.user.avatar.attached? %>
                                    <img src="<%=(url_for(c.user.avatar))%>" class="mr-3 rounded-circle"> 
                                <% end %>
   
                                <div class="media-body">
                                    <div class="row">
                                        <div class="col-8 d-flex">
                                            <h5><%=c.user.username%></h5> <span>- 2 hours ago</span>
                                        </div>

                                        <div class="col-4">
                                            <div class="pull-right reply"> <a href="/articles/<%=@article.id%>/comments/<%=c.id%>/replies/new"><span><i class="fa   fa-reply"></i> reply</span></a></div>
                                        </div>
                                    </div>

                                    <%= c.content %>

                                    <% if current_user.id == c.user_id %>
                                        <%= link_to 'Delete', comment_path(c), method: :delete, data:{Confirm: "Delete?"} %>
                                        <%= link_to 'Edit', edit_comment_path(c) %>
                                    <% end %>
                                         

                                    <% c.replies.collect do |r|%>
                                        <div class="media mt-4"> 
                                            <% if r.user.avatar.attached? %>
                                                <img src="<%=(url_for(r.user.avatar))%>" class="mr-3 rounded-circle"> 
                                            <% end %>
   
                                            <div class="media-body">
                                                <div class="row">
                                                    <div class="col-12 d-flex">
                                                        <h5><%=r.user.username%></h5> <span>- 3 hours ago</span> 
                                                    </div>
                                                </div>

                                                <div>
                                                    <%= r.content %>
                                                    <% if current_user.id == r.user_id%>
                                                        <%= link_to 'Delete', reply_path(r), method: :delete, data:{Confirm: "Delete?"}%> 
                                                        <%= link_to 'Edit', edit_reply_path(r)%>
                                                    <%end%>  
                                                </div>
                                            </div>
                                        </div>
                                    <% end %>
                                </div>
                            </div>    
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>           
</div>

app/views/partials/_errors.html.erb
      <% if instance.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(instance.errors.count, "Error") %>!</h2>
        <ul>
          <% instance.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

app/views/partials/_filter.html.erb
  
<div>
  <h3>Filter articles:</h3>
  <%= form_tag("/articles", method: "get") do %>
    <%= label_tag("Source")%>

    <%= select_tag "source", options_for_select(Article.all_sources), include_blank: true %>
    <%= submit_tag "Filter" %>
  <% end %>
</div>

app/views/partials/_replies.html.erb
<div class="container mb-5 mt-5">
    <div class="card">
        <div class="row">
            <div class="col-md-12">

                <h3 class="text-center mb-5"> Ready: FIGHT! </h3>
                
                <%= render partial: 'partials/errors', locals: {instance: @reply} %>
                <%=form_for @reply do |f|%>
                <%=f.hidden_field :comment_id, :value=> @comment.id%>
                <%=f.label :content, 'Reply:' %><br>
                <%=f.text_area :content %><br>
                <%=f.submit %>
                <%end%>
                <br>
             
                
                <% @article.comments.each do |c| %>

                    <div class="row pb-4">
                        <div class="col-md-12">
                            <div class="media">    
                                <% if c.user.avatar.attached? %>
                                    <img src="<%=(url_for(c.user.avatar))%>" class="mr-3 rounded-circle"> 
                                <% end %>
   
                                <div class="media-body">
                                    <div class="row">
                                        <div class="col-8 d-flex">
                                            <h5><%=c.user.username%></h5> <span>- 2 hours ago</span>
                                        </div>

                                        <div class="col-4">
                                            <div class="pull-right reply"> <a href="/articles/<%=@article.id%>/comments/<%=c.id%>/replies/new"><span><i class="fa   fa-reply"></i> reply</span></a></div>
                                        </div>
                                    </div>

                                    <%= c.content %>
                                      <% if current_user.id == c.user_id%>
                                        <%= link_to 'Delete', comment_path(c), method: :delete, data:{Confirm: "Delete?"}%> 
                                        <%= link_to 'Edit', edit_comment_path(c)%>
                                        <%end%>  
                                       

                                    <% c.replies.collect do |r|%>
                                        <div class="media mt-4"> 
                                            <% if r.user.avatar.attached? %>
                                                <img src="<%=(url_for(r.user.avatar))%>" class="mr-3 rounded-circle"> 
                                            <% end %>
   
                                            <div class="media-body">
                                                <div class="row">
                                                    <div class="col-12 d-flex">
                                                        <h5><%=r.user.username%></h5> <span>- 3 hours ago</span> 
                                                    </div>
                                                </div>

                                                <div>
                                                    <%= r.content %>
                                                    <% if current_user.id == r.user_id%>
                                                        <%= link_to 'Delete', reply_path(r), method: :delete, data:{Confirm: "Delete?"}%> 
                                                        <%= link_to 'Edit', edit_reply_path(r)%>
                                                    <%end%>  
                                                </div>
                                            </div>
                                        </div>
                                    <% end %>
                                </div>
                            </div>    
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>           
</div>