config/routes.rb
  
Rails.application.routes.draw do
  resources :subscriptions
  resources :users
  resources :comments, except: [:show, :index]
  resources :replies, except: [:show, :index]
  
  resources :articles, only: [:index] do
    resources :comments, only: [:index]
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  post 'logout' => 'sessions#destroy'

  get '/top' => 'articles#show' 
  #code challenge

  get 'articles/:id/comments/:id/replies/new' => 'replies#new'
  post 'articles/:id/comments/:id/replies/new' => 'replies#create'

  root to: 'articles#index'

  match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get, :post]
  # match '*path' => 'application#fallback', via: :all, constraints: lambda { |req| req.path.exclude? 'rails/active_storage'}


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :comments
    has_many :articles, through: :comments
    has_many :replies
    has_many :subscriptions
    has_one_attached :avatar
    has_secure_password


    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    before_save { self.email = email.downcase }
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }

    validates :username, presence: true, uniqueness: true
    validates :email, uniqueness: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:show, :edit, :update, :destroy]
    before_action :require_login
    before_action :all_users, only: [:show, :index]
    skip_before_action :require_login, only: [:new, :create] 

    def index
        
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to articles_path
        else
            render :new
        end
    end
    
    def show
        @articles = Article.all.max_by(5){|a| (a.comments.length + a.replies.length)}
    end

    def edit

    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :new           
        end
    end

    def delete
        @user.delete
        redirect_to :new
    end

    private

    def find_user
        @user = User.find_by_id(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :password, :avatar)
    end

    def all_users
        @users = User.all
    end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/edit.html.erb
<br>
<br>
<main class="form-signin">

  <%= form_for @user do |f| %>

    <div class="text-center mb-4">
      <%= image_tag "divideicon2.png", class: 'mb-4', style: 'height: 100px; width: 100px;' %>
      <h2>DivisioN</h2>
    </div>
  
    <%= f.label 'Profile Photo' %>:
    <%= f.file_field :avatar, class: "form-control btn-sm" %><br>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
  <% end %>
  <p class="mt-5 mb-3 text-muted text-center">&copy; 2021 2-Slice-Gaming</p>
</main>
   






 
 
 
 
 
 
 
 
 

app/views/users/index.html.erb
   <div class="col-md-2">
            <div class="list-group">    
                &nbsp&nbsp&nbsp<h1>&nbsp&nbsp&nbsp Users List!</h1>
               
                <%@users.each do |u| %>
                    <% if u.avatar.attached? %>
                <li class="list-group-item list-group-item-action list-group-item-dark bg-primary" ><img src="<%=(url_for(u.avatar)) %>" style="width: 50px; height: 50px; border-radius: 50px"> &nbsp&nbsp <%=link_to "#{u.username}", user_path(u), class: "text-light" %></li>
                    <% end %>
                    
      
                <% end %>  
            </div>
        </div>
    </div>

app/views/users/new.html.erb
    <br>
    <br>
    <main class="form-signin">

      <%= form_for(:user, url: users_path) do |f| %>

      <div class="text-center mb-4">
        <%= image_tag "divideicon2.png", class: 'mb-4', style: 'height: 100px; width: 100px;' %>
        
        <h2>DivisioN</h2>
      </div>


      <div class="form-label-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %><br>
      </div>

      <div class="form-label-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %><br>
        </div>

      <div class="form-label-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %><br>
      </div>

      <div class="form-label-group">
        <%= f.label 'Profile Photo' %>
        <%= f.file_field :avatar, class: "form-control btn" %><br>
      </div>

      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>

      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>

        <%= link_to "Sign up with Google", '/auth/google_oauth2', method: :post, class: "button btn btn-lg btn-primary btn-block" %>
        
      <% end %>

      <%= render partial: 'partials/errors', locals: {instance: @user} %>

      <p class="mt-5 mb-3 text-muted text-center">&copy; 2021 2-Slice-Gaming</p>
    </main>
   

app/views/users/show.html.erb
<main role="main">

        <br>
      <div class="container">
            <!-- Example row of columns -->
            <div class="row">
                <div class="col-md-7">
                    <h1 class="text-center">Trending Arguments</h1><br>
                    <%@articles.each do |article|%>
                    <% article.comments.each do |r| r.replies%>
                    <% end %>

                    <ul class="card text-center border-dark mb-3 shadow-sm p-3 bg-white rounded">
                        <h2><strong><%= article.title %></h2></strong><br>
                        <h4 class="text-center card border-secondary p-2">Source: <%=article.source%></h4>
                        <p><em><%= article.description.first(250)%></em></p>
                        <p> <%=link_to "View Details:", article.url, class: "btn btn-secondary",    role: "button"%>&nbsp <%=link_to "Comments: (#{article.comments.length + article.replies.length})   ", article_comments_path(article), class: "btn btn-secondary" %></p>
                    </ul>

                    <% end %>
                </div>

                <div class="col-md-5">
                    <h1 class="text-center"><%= @user.username %> </h1><br>
                       
                        
                        
                    <% if @user.avatar.attached? %>
                    <img src="<%=(url_for(@user.avatar))%>" class="img-fluid img-thumbnail" style= "height: 470px; width: 470px;"> 
                    <% end %>
                    <h3 class="text-center"><%= @user.email %></h3><br>

                    <h2 class="text-center">Users</h2>
                    <div class="list-group">    
                        
                        <%@users.each do |u| %>
                        <% if u.avatar.attached? %>
                        <li class="list-group-item list-group-item-action list-group-item-dark bg-secondary" ><img src="<%=(url_for(u.avatar)) %>" style="width: 50px; height: 50px; border-radius: 50px"> &nbsp&nbsp <%=link_to "#{u.username}", user_path(u), class: "text-light" %></li>
                        <% end %>
                    
      
                        <% end %>  
                    </div>    
                   
                </div>

            </div>
        </div> <!-- /container -->

    </main>

    <footer class="container">
      <p>&copy; 2021 2-Slice-Gaming</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>